######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 24 01:24:53 2015
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++11 -g -Wall

# Input
HEADERS += main_window.h disease.h disease_widget.h webDr.h
SOURCES += main.cpp main_window.cpp disease.cpp disease_widget.cpp webDr.cpp
